// GENERATED by scripts/capture.mjs. Do not edit: every value here was read from the thing
// that produces it, and a hand edit makes this file stop being that.
//
//   the surface   parserail-mcp/dist/index.js, over stdio, tools/list
//   the prices    https://parserail.thecompound.tech/pricing.json
//   async         https://parserail.thecompound.tech/openapi.json
//   collections   ~/CompoundLabs/parserail/src/lib/platform/constants.ts
export const CAPTURED_AT = "2026-10-02";
export const SERVER = {
 "name": "parserail-mcp",
 "version": "0.5.7",
 "protocol": "2025-06-18",
 "capabilities": [
  "tools"
 ],
 "stderr": "[parserail-mcp] ParseRail MCP server running on stdio."
} as const;
export const CREDIT_USD = 0.01;
export const TOOLS = [
 {
  "name": "parserail_parse",
  "key": "parse",
  "title": "Document parse",
  "description": "Any invoice, receipt, EOB, ERA, or COI, PDF or image, into structured, validated JSON. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "fileUrl",
   "text",
   "fileBase64",
   "fileMimeType",
   "docType"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_extract",
  "key": "extract",
  "title": "Field extraction",
  "description": "Pull a field set you define out of any block of text. You name the fields; you get typed values with confidence. Costs credits from the account wallet.",
  "required": [
   "text",
   "fields"
  ],
  "optional": [
   "instructions"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_classify",
  "key": "classify",
  "title": "Classification",
  "description": "Route or tag text against your own taxonomy, a label, a confidence, and a one-line rationale. Costs credits from the account wallet.",
  "required": [
   "text",
   "labels"
  ],
  "optional": [
   "multi",
   "instructions"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_summarize",
  "key": "summarize",
  "title": "Summarize",
  "description": "A meeting transcript, thread, or report → a tight summary, key points, and extracted action items. Costs credits from the account wallet.",
  "required": [
   "text"
  ],
  "optional": [
   "length",
   "actionItems"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_redact",
  "key": "redact",
  "title": "PII redaction",
  "description": "Detect and strip names, emails, phones, SSNs, cards, and PHI from text before you store or log it. Costs credits from the account wallet.",
  "required": [
   "text"
  ],
  "optional": [
   "types",
   "placeholder"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_sentiment",
  "key": "sentiment",
  "title": "Sentiment",
  "description": "Turn a review or support message into a sentiment score, per-aspect breakdown, and the themes driving it. Costs credits from the account wallet.",
  "required": [
   "text"
  ],
  "optional": [
   "aspects"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_contract",
  "key": "contract",
  "title": "Contract analysis",
  "description": "A contract → parties, effective date, term, renewal, governing law, obligations, and flagged risk clauses. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "fileUrl",
   "text",
   "fileBase64",
   "fileMimeType"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_chargeback",
  "key": "chargeback",
  "title": "Chargeback representment",
  "description": "Dispute details → a representment narrative, an evidence checklist, the right reason code, and a win-likelihood. Costs credits from the account wallet.",
  "required": [
   "reason",
   "transaction"
  ],
  "optional": [
   "evidence",
   "context",
   "network"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_enrich",
  "key": "enrich",
  "title": "Company enrichment",
  "description": "A domain or work email → a structured company profile: name, description, industry, HQ, size, and links. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "domain",
   "email"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_invoice",
  "key": "invoice",
  "title": "Invoice extraction",
  "description": "An invoice, PDF, photo, or text, into vendor, dates, PO refs, tax, totals, and clean line items. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "fileUrl",
   "text",
   "fileBase64",
   "fileMimeType"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_receipt",
  "key": "receipt",
  "title": "Receipt extraction",
  "description": "A receipt into merchant, items, totals, payment method, and an expense category, built for expense flows. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "fileUrl",
   "text",
   "fileBase64",
   "fileMimeType"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_statement",
  "key": "statement",
  "title": "Statement parsing",
  "description": "A bank or card statement into the account, the period, balances, and every transaction as a normalized row. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "fileUrl",
   "text",
   "fileBase64",
   "fileMimeType"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_resume",
  "key": "resume",
  "title": "Resume parsing",
  "description": "A resume or CV into a structured candidate profile: contact, skills, experience, education, and links. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "fileUrl",
   "text",
   "fileBase64",
   "fileMimeType"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_tables",
  "key": "tables",
  "title": "Table extraction",
  "description": "Every table in a document, even scanned, as clean headers and rows, ready for your spreadsheet or DB. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "fileUrl",
   "text",
   "fileBase64",
   "fileMimeType"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_split",
  "key": "split",
  "title": "Document splitting",
  "description": "A multi-document scan bundle classified and split: what each document is, where it starts and ends, and a summary. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "fileUrl",
   "text",
   "fileBase64",
   "fileMimeType"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_compare",
  "key": "compare",
  "title": "Document comparison",
  "description": "Two versions of a contract or document → every material change, what it means, and the risk it carries. Costs credits from the account wallet.",
  "required": [
   "a",
   "b"
  ],
  "optional": [],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_structure",
  "key": "structure",
  "title": "Structure to your schema",
  "description": "Any messy input, text, HTML, an email, plus YOUR JSON schema → output shaped to it, validated against your required fields and property types, with an automatic corrective retry and a `valid` flag. Costs credits from the account wallet.",
  "required": [
   "input",
   "schema"
  ],
  "optional": [
   "instructions"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_normalize",
  "key": "normalize",
  "title": "Record normalization",
  "description": "A batch of messy records → clean canonical rows, with a change log of every fix (casing, formats, dedup-ready values). Costs credits from the account wallet.",
  "required": [
   "records"
  ],
  "optional": [
   "fields",
   "instructions"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_match",
  "key": "match",
  "title": "Entity matching",
  "description": "Two record sets → which rows are the same real-world thing, with confidence and reasoning. Fuzzy names, typos, aliases handled. Costs credits from the account wallet.",
  "required": [
   "a",
   "b"
  ],
  "optional": [
   "keys"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_categorize",
  "key": "categorize",
  "title": "Batch categorization",
  "description": "Up to a hundred items against your taxonomy in one call, products, transactions, tickets, each with a confidence. Costs credits from the account wallet.",
  "required": [
   "items",
   "taxonomy"
  ],
  "optional": [
   "multi",
   "instructions"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_dunning",
  "key": "dunning",
  "title": "Collections sequence",
  "description": "An overdue invoice → a ready-to-send collection sequence, escalating at the right pace and tone for how late it is. Costs credits from the account wallet.",
  "required": [
   "invoice",
   "customer"
  ],
  "optional": [
   "tone",
   "channel",
   "steps"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_po_match",
  "key": "po-match",
  "title": "3-way match",
  "description": "Invoice vs purchase order vs receipt → matched, partial, or mismatched, with every discrepancy flagged and sized. Costs credits from the account wallet.",
  "required": [
   "invoice",
   "purchaseOrder"
  ],
  "optional": [
   "receipt",
   "tolerancePct"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_quote",
  "key": "quote",
  "title": "Quote builder",
  "description": "A job description plus your rates → an itemized, professional quote with assumptions and scope notes spelled out. Costs credits from the account wallet.",
  "required": [
   "job"
  ],
  "optional": [
   "rates",
   "pastQuotes",
   "currency"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_fraud_flag",
  "key": "fraud-flag",
  "title": "Fraud triage",
  "description": "An order or transaction in context → a risk score, the signals driving it, and the checks worth running before you ship. Costs credits from the account wallet.",
  "required": [
   "order"
  ],
  "optional": [
   "context"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_reply",
  "key": "reply",
  "title": "Reply drafting",
  "description": "A customer thread plus your context → a ready-to-send reply in the right tone, with an internal note for the agent. Costs credits from the account wallet.",
  "required": [
   "thread"
  ],
  "optional": [
   "context",
   "tone",
   "goal",
   "senderName"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_triage",
  "key": "triage",
  "title": "Ticket triage",
  "description": "A support ticket → priority, category, the team it belongs to, sentiment, SLA risk, and a suggested first response. Costs credits from the account wallet.",
  "required": [
   "ticket"
  ],
  "optional": [
   "categories",
   "teams"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_minutes",
  "key": "minutes",
  "title": "Meeting minutes",
  "description": "A meeting transcript → clean minutes: summary, decisions made, action items with owners, and open questions. Costs credits from the account wallet.",
  "required": [
   "transcript"
  ],
  "optional": [
   "attendees"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_outreach",
  "key": "outreach",
  "title": "Outreach sequence",
  "description": "An enriched lead plus what you sell → a personalized outreach sequence that references what actually makes them a fit. Costs credits from the account wallet.",
  "required": [
   "lead",
   "product"
  ],
  "optional": [
   "sender",
   "channel",
   "steps"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_review_reply",
  "key": "review-reply",
  "title": "Review response",
  "description": "A customer review → a brand-safe public response, the issues to log, and whether it needs human escalation. Costs credits from the account wallet.",
  "required": [
   "review"
  ],
  "optional": [
   "rating",
   "business",
   "resolution"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_moderate",
  "key": "moderate",
  "title": "Content moderation",
  "description": "Text or an image against YOUR policy → allow, review, or block, with the categories and excerpts that drove the call. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "text",
   "image",
   "imageUrl",
   "policy"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_rewrite",
  "key": "rewrite",
  "title": "Brand-voice rewrite",
  "description": "Any copy → your brand voice. Describe the voice or paste a sample; get the rewrite and what changed. Costs credits from the account wallet.",
  "required": [
   "text"
  ],
  "optional": [
   "voice",
   "goal",
   "audience",
   "length"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_product_copy",
  "key": "product-copy",
  "title": "Product copy",
  "description": "Specs and an audience → listing-ready titles, bullets, a description, and SEO keywords, per channel. Costs credits from the account wallet.",
  "required": [
   "product"
  ],
  "optional": [
   "channel"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_describe",
  "key": "describe",
  "title": "Image description",
  "description": "An image → accessible alt text, a caption, tags, and any text found inside it. Accessibility and catalogs in one call. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "image",
   "imageUrl",
   "purpose"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_research",
  "key": "research",
  "title": "Research brief",
  "description": "A company or topic → a multi-source, citation-backed brief: what it is, what changed lately, and what matters. Real web work. Costs credits from the account wallet.",
  "required": [
   "query"
  ],
  "optional": [
   "focus",
   "depth"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_screen",
  "key": "screen",
  "title": "Lead screening",
  "description": "A lead plus your ICP criteria → a web-grounded qualification verdict with the evidence for and against. Costs credits from the account wallet.",
  "required": [
   "lead",
   "criteria"
  ],
  "optional": [],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_transcribe",
  "key": "transcribe",
  "title": "Transcription",
  "description": "An audio recording → accurate text with speakers and paragraph timestamps. Meetings, calls, voice notes. Costs credits from the account wallet.",
  "required": [],
  "optional": [
   "audio",
   "audioUrl",
   "diarize",
   "language"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_memory",
  "key": "memory",
  "title": "Agent memory",
  "description": "Store, search, and forget memories for your agents, semantic recall on your own namespace, no vector DB to run. Costs credits from the account wallet.",
  "required": [
   "op"
  ],
  "optional": [
   "namespace",
   "content",
   "metadata",
   "query",
   "limit",
   "id"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_image",
  "key": "image",
  "title": "Image generation",
  "description": "A prompt → a production-ready image. Marketing visuals, product scenes, and consistent brand imagery. Costs credits from the account wallet.",
  "required": [
   "prompt"
  ],
  "optional": [
   "style",
   "aspectRatio"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_speak",
  "key": "speak",
  "title": "Text to speech",
  "description": "Text → natural speech audio, ready to embed. Voice notes, IVR lines, narration. Costs credits from the account wallet.",
  "required": [
   "text"
  ],
  "optional": [
   "voice",
   "pace"
  ],
  "readOnly": false,
  "idempotent": false
 },
 {
  "name": "parserail_account",
  "key": "account",
  "title": "Account balance",
  "description": "Get the authenticated account's credit balance.",
  "required": [],
  "optional": [],
  "readOnly": true,
  "idempotent": true
 },
 {
  "name": "parserail_late_fee_rules",
  "key": "late-fee-rules",
  "title": "US late-fee ceilings by state",
  "description": "Look up the maximum late-fee/interest rate a US state allows on a commercial (B2B) invoice, with the statute cite. Statute-verified conservative safe floors. Free, costs no credits.",
  "required": [],
  "optional": [
   "state"
  ],
  "readOnly": true,
  "idempotent": true
 }
] as const;
export const PRICES = {
 "parse": {
  "credits": 10,
  "usd": 0.1,
  "unit": "document",
  "available": true
 },
 "extract": {
  "credits": 4,
  "usd": 0.04,
  "unit": "call",
  "available": true
 },
 "classify": {
  "credits": 2,
  "usd": 0.02,
  "unit": "call",
  "available": true
 },
 "summarize": {
  "credits": 3,
  "usd": 0.03,
  "unit": "call",
  "available": true
 },
 "redact": {
  "credits": 3,
  "usd": 0.03,
  "unit": "call",
  "available": true
 },
 "sentiment": {
  "credits": 2,
  "usd": 0.02,
  "unit": "call",
  "available": true
 },
 "contract": {
  "credits": 12,
  "usd": 0.12,
  "unit": "contract",
  "available": true
 },
 "chargeback": {
  "credits": 15,
  "usd": 0.15,
  "unit": "dispute",
  "available": true
 },
 "enrich": {
  "credits": 5,
  "usd": 0.05,
  "unit": "lookup",
  "available": true
 },
 "invoice": {
  "credits": 8,
  "usd": 0.08,
  "unit": "invoice",
  "available": true
 },
 "receipt": {
  "credits": 6,
  "usd": 0.06,
  "unit": "receipt",
  "available": true
 },
 "statement": {
  "credits": 12,
  "usd": 0.12,
  "unit": "statement",
  "available": true
 },
 "resume": {
  "credits": 8,
  "usd": 0.08,
  "unit": "resume",
  "available": true
 },
 "tables": {
  "credits": 8,
  "usd": 0.08,
  "unit": "document",
  "available": true
 },
 "split": {
  "credits": 10,
  "usd": 0.1,
  "unit": "bundle",
  "available": true
 },
 "compare": {
  "credits": 15,
  "usd": 0.15,
  "unit": "comparison",
  "available": true
 },
 "structure": {
  "credits": 6,
  "usd": 0.06,
  "unit": "call",
  "available": true
 },
 "normalize": {
  "credits": 5,
  "usd": 0.05,
  "unit": "batch",
  "available": true
 },
 "match": {
  "credits": 8,
  "usd": 0.08,
  "unit": "run",
  "available": true
 },
 "categorize": {
  "credits": 3,
  "usd": 0.03,
  "unit": "batch",
  "available": true
 },
 "dunning": {
  "credits": 8,
  "usd": 0.08,
  "unit": "sequence",
  "available": true
 },
 "po-match": {
  "credits": 10,
  "usd": 0.1,
  "unit": "match",
  "available": true
 },
 "quote": {
  "credits": 8,
  "usd": 0.08,
  "unit": "quote",
  "available": true
 },
 "fraud-flag": {
  "credits": 6,
  "usd": 0.06,
  "unit": "check",
  "available": true
 },
 "reply": {
  "credits": 5,
  "usd": 0.05,
  "unit": "reply",
  "available": true
 },
 "triage": {
  "credits": 3,
  "usd": 0.03,
  "unit": "ticket",
  "available": true
 },
 "minutes": {
  "credits": 6,
  "usd": 0.06,
  "unit": "transcript",
  "available": true
 },
 "outreach": {
  "credits": 6,
  "usd": 0.06,
  "unit": "sequence",
  "available": true
 },
 "review-reply": {
  "credits": 3,
  "usd": 0.03,
  "unit": "review",
  "available": true
 },
 "moderate": {
  "credits": 2,
  "usd": 0.02,
  "unit": "item",
  "available": true
 },
 "rewrite": {
  "credits": 3,
  "usd": 0.03,
  "unit": "call",
  "available": true
 },
 "product-copy": {
  "credits": 5,
  "usd": 0.05,
  "unit": "product",
  "available": true
 },
 "describe": {
  "credits": 3,
  "usd": 0.03,
  "unit": "image",
  "available": true
 },
 "research": {
  "credits": 50,
  "usd": 0.5,
  "unit": "brief",
  "available": true
 },
 "screen": {
  "credits": 10,
  "usd": 0.1,
  "unit": "lead",
  "available": true
 },
 "transcribe": {
  "credits": 10,
  "usd": 0.1,
  "unit": "recording",
  "available": false
 },
 "memory": {
  "credits": 2,
  "usd": 0.02,
  "unit": "operation",
  "available": true
 },
 "image": {
  "credits": 10,
  "usd": 0.1,
  "unit": "image",
  "available": true
 },
 "speak": {
  "credits": 5,
  "usd": 0.05,
  "unit": "clip",
  "available": true
 }
} as const;
export const ASYNC = [
 "parse",
 "contract",
 "invoice",
 "receipt",
 "statement",
 "resume",
 "tables",
 "split",
 "compare"
] as const;
export const COLLECTIONS = [
 {
  "key": "documents",
  "title": "Documents",
  "blurb": "Any document in. Clean, schema-valid JSON out."
 },
 {
  "key": "extract",
  "title": "Extract & structure",
  "blurb": "Messy input → data your code can trust."
 },
 {
  "key": "commerce",
  "title": "Commerce & ops",
  "blurb": "Disputes, collections, quotes, and fraud — handled."
 },
 {
  "key": "communication",
  "title": "Communication",
  "blurb": "Replies, triage, minutes, and outreach, ready to send."
 },
 {
  "key": "content",
  "title": "Content & moderation",
  "blurb": "On-brand copy in; policy-breaking content out."
 },
 {
  "key": "web",
  "title": "Web & research",
  "blurb": "Live, cited answers from the real web."
 },
 {
  "key": "media",
  "title": "Media & agents",
  "blurb": "Voice, images, transcripts — and memory that persists."
 }
] as const;
export const COLLECTION_OF: Record<string, string> = {
 "parse": "documents",
 "extract": "extract",
 "classify": "extract",
 "summarize": "communication",
 "redact": "content",
 "sentiment": "communication",
 "contract": "documents",
 "chargeback": "commerce",
 "enrich": "web",
 "invoice": "documents",
 "receipt": "documents",
 "statement": "documents",
 "resume": "documents",
 "tables": "documents",
 "split": "documents",
 "compare": "documents",
 "structure": "extract",
 "normalize": "extract",
 "match": "extract",
 "categorize": "extract",
 "dunning": "commerce",
 "po-match": "commerce",
 "quote": "commerce",
 "fraud-flag": "commerce",
 "reply": "communication",
 "triage": "communication",
 "minutes": "communication",
 "outreach": "communication",
 "review-reply": "communication",
 "moderate": "content",
 "rewrite": "content",
 "product-copy": "content",
 "describe": "content",
 "research": "web",
 "screen": "web",
 "transcribe": "media",
 "memory": "media",
 "image": "media",
 "speak": "media"
};
export const RATE_PER_MINUTE: Record<string, number> = {
 "parse": 60,
 "extract": 120,
 "classify": 300,
 "summarize": 120,
 "redact": 120,
 "sentiment": 300,
 "contract": 30,
 "chargeback": 30,
 "enrich": 60,
 "invoice": 60,
 "receipt": 60,
 "statement": 30,
 "resume": 60,
 "tables": 60,
 "split": 30,
 "compare": 30,
 "structure": 120,
 "normalize": 60,
 "match": 30,
 "categorize": 120,
 "dunning": 60,
 "po-match": 60,
 "quote": 60,
 "fraud-flag": 120,
 "reply": 120,
 "triage": 300,
 "minutes": 60,
 "outreach": 60,
 "review-reply": 120,
 "moderate": 300,
 "rewrite": 120,
 "product-copy": 120,
 "describe": 120,
 "research": 10,
 "screen": 30,
 "transcribe": 30,
 "memory": 300,
 "image": 30,
 "speak": 60
};
